"""Participants

Revision ID: 1137421798bb
Revises: 32e4c9ad92ef
Create Date: 2024-03-22 23:26:24.113608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1137421798bb'
down_revision: Union[str, None] = '32e4c9ad92ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_participants',
    sa.Column('travel_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], name=op.f('fk_travel_participants_participant_id_users'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['travel_id'], ['travels.id'], name=op.f('fk_travel_participants_travel_id_travels'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_travel_participants')),
    sa.UniqueConstraint('travel_id', 'participant_id', name=op.f('uq_travel_participants_travel_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_participants')
    # ### end Alembic commands ###
